### ISSUE TITLE
Disabling a language server for a project causes an error to be logged

### ISSUE THREAD

**Issue by saagarjha** [sublimelsp/LSP#1105]
When I try to disable a language server for a project, I get the following error in the console:

```
Traceback (most recent call last):
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/configuration.py", line 80, in _on_done
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 393, in disable_config
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 383, in update_configs
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/configurations.py", line 59, in update
    self.all = self._create_window_configs()
  File "/Users/saagarjha/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/configurations.py", line 77, in _create_window_configs
    project_clients_dict = (self._window.project_data() or {}).get("settings", {}).get("LSP", {})
AttributeError: 'str' object has no attribute 'get'
```

I've installed SublimeLSP from Package Control, and am using Sublime Text Build 4074 (so I think it should be using the st4000-exploration code?) I am on macOS Catalina 10.15.5 (19F101) and trying to enable the built-in clangd server for the project, and disabling my "clangd-c" server which exists solely to provide a mediocre fallback for projects without a compile_commands.json:

```json
"clangd-c": {
	"enabled": true,
	"command": [
		"clangd",
		"--completion-style=detailed",
		"--compile-commands-dir",
		"~/.clangd/c"
	],
	"syntaxes": ["Packages/C++/C.sublime-syntax"],
	"languageId": "c",
}
```

I did a little bit of digging and it seems like the `self._window.project_data()` on that line seems to return the string "Packages/C++/C.sublime-syntax", although I don't know enough to figure out why…

**Comment by rwols** [comment]
In the ST console, you can run

```
window.project_data()
```
to verify this. For me, it prints for example
```
>>> window.project_data()
{'folders': [{'path': 'C:\\Users\\rachwols\\AppData\\Roaming\\Sublime Text 3\\Packages\\User'}], 'settings': {'LSP': {'texlab': {'enabled': True}}}}
```

**Comment by saagarjha** [comment]
I'm getting that error even though `window.project_data()` seems like a sane, valid dictionary…it does seem to have set the value correctly, though, based on the data I get back:

```
>>> window.project_data()
{'folders': [{'path': '/Users/saagarjha/Git/ish'}], 'settings': {'LSP': {'clangd-c': {'enabled': False}}}}
```

**Comment by rwols** [comment]
Presumably you figured out the problem. Feel free to open another issue if you get stuck with configuration.
