### ISSUE TITLE
After installation, LSP cannot run

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP#1186]
Your issue may have been solved already - please search before creating new!

Troubleshooting guide: https://lsp.readthedocs.io/en/latest/troubleshooting
Chat: https://discord.gg/RMkk5MR
Miscellaneous notes (anyone can edit!): https://github.com/sublimelsp/LSP/wiki/Notes

Is it a language server problem? The LSP package can do little to prevent slowness or missing content - please check their support materials!

Please include in your report:

* OS and language server
* How you installed LSP (Package Control or from git?)
Package Control
* Minimal reproduction steps
* Log
```
Traceback (most recent call last):
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 813, in on_query_context
    val = callback(key, operator, operand, match_all)
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 129, in profiler
    return event_handler(*args)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 161, in on_query_context
    if any(self.sessions(capability)):
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 45, in sessions
    yield from self.manager.sessions(self.view, capability)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 30, in manager
    self._manager = windows.lookup(window)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
    raise RuntimeError("no settings")
```
sublime Version 4074
Requesting a feature?

Please read https://github.com/sublimelsp/LSP/blob/master/CONTRIBUTING.md. Specifically, LSP avoids building functionality that does not exist in Sublime Text, or that serves only one language.

**Comment by rwols** [comment]
Please run `Package Control: Satisfy Dependencies` from the command palette, and then restart SublimeText. Does that solve the problem?

**Comment by jfcherng** [comment]
May related to https://github.com/sublimelsp/LSP-html/issues/9#issuecomment-657279628

**Comment by jingyuexing** [comment]
> 
> 
> Please run `Package Control: Satisfy Dependencies` from the command palette, and then restart SublimeText. Does that solve the problem?

thanks, This is the problem of settings，now it's done

**Comment by rwols** [comment]
@jingyuexing were you previously on ST3? Is this the first time that you started LSP with ST4?

**Comment by jingyuexing** [comment]
> 
> 
> @jingyuexing were you previously on ST3? Is this the first time that you started LSP with ST4?

```
The following incompatible package was found installed:

LSP

This is usually due to syncing packages across different machines in a way that does not check package metadata for compatibility.

Please visit https://packagecontrol.io/docs/syncing for information about how to properly sync configuration and packages across machines.

To restore package functionality, please remove each listed package and reinstall it.
```

**Comment by jingyuexing** [comment]
> 
> 
> > Please run `Package Control: Satisfy Dependencies` from the command palette, and then restart SublimeText. Does that solve the problem?
> 
> thanks, This is the problem of settings，now it's done

sublime Version 4047

**Comment by rchl** [comment]
> The following incompatible package was found installed:

So LSP would get updated to compatible version automatically on next update check and then things would work. You could also manually update using `Package Control: Upgrade Package` to speed it up.

**Comment by jingyuexing** [comment]
> 
> 
> > The following incompatible package was found installed:
> 
> So LSP would get updated to compatible version automatically on next update check and then things would work. You could also manually update using `Package Control: Upgrade Package` to speed it up.

```
File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 114, in on_activated_async
    self._register_async()
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 262, in _register_async
    self.manager.register_listener_async(self)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 30, in manager
    self._manager = windows.lookup(window)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
    raise RuntimeError("no settings")
RuntimeError: no settings
Traceback (most recent call last):
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/types.py", line 31, in run
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 220, in _do_highlights
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 48, in session
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 69, in _best_session
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 45, in sessions
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 30, in manager
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
RuntimeError: no settings
Traceback (most recent call last):
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/types.py", line 31, in run
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 180, in _do_code_actions
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/diagnostics.py", line 54, in view_diagnostics
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
RuntimeError: no settings
Traceback (most recent call last):
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 795, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 622, in run_view_callbacks
    callback(*args)
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 167, in exception_handler
    return event_handler(*args)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 114, in on_activated_async
    self._register_async()
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 262, in _register_async
    self.manager.register_listener_async(self)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 30, in manager
    self._manager = windows.lookup(window)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
    raise RuntimeError("no settings")
RuntimeError: no settings
Traceback (most recent call last):
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 795, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 622, in run_view_callbacks
    callback(*args)
  File "D:\sublime_text_4074_x64\Lib\python33\sublime_plugin.py", line 167, in exception_handler
    return event_handler(*args)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 114, in on_activated_async
    self._register_async()
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/documents.py", line 262, in _register_async
    self.manager.register_listener_async(self)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 30, in manager
    self._manager = windows.lookup(window)
  File "D:\sublime_text_4074_x64\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 353, in lookup
    raise RuntimeError("no settings")
RuntimeError: no settings
```

**Comment by rchl** [comment]
Maybe post the console log since the start of ST. Might reveal the root issue.

**Comment by rchl** [comment]
The linked PC feature request is resolved so the update should trigger immediately on updating to new ST version. I think that was the issue here.
