### ISSUE TITLE
Crash when loading plugin

### ISSUE THREAD

**Issue by xldenis** [sublimelsp/LSP#1382]
**Describe the bug**
I noticed that the LSP plugin seemed to have stopped working on my installation. When I looked at the console I saw this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/boot.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 34, in <module>
AttributeError: 'module' object has no attribute 'KIND_ID_NAVIGATION'
```

I've tried re-installing the plugin to no avail. 

**To Reproduce**
1. Open Sublime
2. Check console

**Environment (please complete the following information):**
- OS: macOS 10.14.6
- Sublime Text: dev channel, 3210
- LSP version: v2020.10.18.18.50.36
- Language servers used: hie, rust-analyzer

**Comment by rwols** [comment]
You seem to be using the st4000-exploration git branch. This branch only works on an alpha build of ST. Checkout the master branch for ST3.

**Comment by xldenis** [comment]
I installed LSP through Package Control, how do I switch the branch?

**Comment by xldenis** [comment]
Never mind, I just saw that I had added this repository in my Package Control.

**Comment by xldenis** [comment]
that worked! sorry about the issue!
