### ISSUE TITLE
LSP not starting due to pygments.formatter import

### ISSUE THREAD

**Issue by kornelski** [sublimelsp/LSP#1396]
**Describe the bug**
After installing LSP via package control, the option to enable LSP doesn't show up. Sublime's console shows it failed to boot.

**To Reproduce**
1. Install LSP 0.13.1 

**Expected behavior**
It should be able to import all it needs

**Environment (please complete the following information):**
- OS: macOS 10.15.7
- Sublime Text version: 3 build 3211
- LSP version: v0.13.1
- Language servers used: gopls, rls (not relevant)

```
python3 --version
Python 3.8.6
```

**Additional context**

From the sublime console:

```
reloading plugin LSP.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/boot.py", line 2, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/code_actions.py", line 6, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/registry.py", line 11, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 4, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/message_request_handler.py", line 4, in <module>
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 19, in <module>
    from .st_scheme_template import SchemeTemplate, POPUP, PHANTOM, SHEET
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_scheme_template.py", line 22, in <module>
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments.formatters'
```

However, pygments is installed:

<img width="215" alt="Screenshot 2020-10-27 at 17 48 21" src="https://user-images.githubusercontent.com/72159/97341189-a351f200-187c-11eb-9e3f-c60caae0489c.png">

pygments/dependency-metadata.json is:

```json
{"version": "2.0.2", "description": "Python pygments module", "platforms": ["*"], "url": "https://github.com/packagecontrol/pygments/issues", "sublime_text": "*"}
```

**Comment by rchl** [comment]
Does `pygmenets` directory look something like this:

![Screenshot 2020-10-27 at 18 58 10](https://user-images.githubusercontent.com/153197/97342354-6985e900-1886-11eb-905c-9e38bb84bcda.png)

?

It hasn't been updated in years so nothing should have broken there.

**Comment by rchl** [comment]
Otherwise please post the console log from ST loading after restarting it. Some dependencies might not be loaded.

**Comment by kornelski** [comment]
<img width="396" alt="Screenshot 2020-10-27 at 18 05 28" src="https://user-images.githubusercontent.com/72159/97343144-0ba1d300-187f-11eb-99c7-ef3ffb0eef7d.png">

The __init__.py file contains:

```python
    :copyright: Copyright 2006-2017 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""
import sys

from pygments.util import StringIO, BytesIO

__version__ = '2.3.1'
__docformat__ = 'restructuredtext'
```

**Comment by kornelski** [comment]
Same error after restart

**Comment by kornelski** [comment]
<img width="224" alt="Screenshot 2020-10-27 at 18 07 17" src="https://user-images.githubusercontent.com/72159/97343332-4441ac80-187f-11eb-87f9-f583aec571b2.png">

**Comment by rchl** [comment]
That looks fine but I think the log from the ST console should help.

**Comment by rwols** [comment]
This is a dependency of mdpopups. Perhaps @facelessuser has more experience with this :)

**Comment by jwortmann** [comment]
Note that the folder hierarchy from @kornelski is different and shows an additional `pygments` folder level. You seem to have a newer version installed than what is distributed by package control (2.1a0): https://github.com/packagecontrol/pygments

**Comment by facelessuser** [comment]
Yes, currently, pygments is fairly old, so if you are using something other than what PC distributes, then 🤷 . Even the Markdown package is fairly old, though I do plan to update that sometime soon as I have control of that repo, I was just waiting for their new HTML parser to have all the major bugs worked out.e

This is the one problem with some of the dependencies, I don't control all the updates down the pipe.

**Comment by kornelski** [comment]
Thanks for investigating it! I didn't update it manually. Could another Sublime extension have updated it?

**Comment by rwols** [comment]
@kornelski were you able to get the pygments dependency to work?

**Comment by kornelski** [comment]
Yes. I've deleted the pygments directory, and ST has reinstalled the correct version.
