### ISSUE TITLE
Exception after latest update

### ISSUE THREAD

**Issue by FichteFoll** [sublimelsp/LSP#1543]
**Describe the bug**
I found the following in my ST console after I lauchend ST and LSP was updated by PC:

```
reloading python 3.3 plugin LSP.boot
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1661, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/boot.py", line 32, in <module>
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1661, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/code_actions.py", line 6, in <module>
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1661, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/registry.py", line 5, in <module>
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1661, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 20, in <module>
ImportError: cannot import name Sequence
```
and also these later (seemingly after the LSP plugins were updated):
```
Traceback (most recent call last):
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 66, in run
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/settings.py", line 23, in _notify_listener
  File "/home/fichte/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 21, in update
AttributeError: 'NoneType' object has no attribute 'windows'
…
LSP: couldn't find a text change listener for ViewListener(13)
```

No `LSP:` commands can be found in the command palette, indicating that it must have failed to load.

**Environment (please complete the following information):**
- OS: Arch Linux
- Sublime Text version: 4094
- LSP version: now 1.2.7

**Comment by FichteFoll** [comment]
I should also note that a restart fixed it.
