### ISSUE TITLE
The Unicode decode Error

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP#1595]
**Describe the bug**

**To Reproduce**
1. install ruby 
2. check utf-8 as the default encoding option
3. see error

**Expected behavior**
Traceback (most recent call last):
  File "D:\sublime_text_3211\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "D:\sublime_text_3211\Data\Installed Packages\LSP-typescript.sublime-package\plugin.py", line 10, in plugin_loaded
    LspTypescriptPlugin.setup()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 64, in setup
    cls.__server.setup()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 70, in setup
    self._copy_to_cache()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 94, in _copy_to_cache
    ResourcePath(src_path).copytree(cache_server_path, exist_ok=True)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 605, in copytree
    for resource in self.rglob('*'):
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 545, in rglob
    return self.glob('**/' + pattern)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 532, in glob
    return ResourcePath.glob_resources(base + pattern)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 199, in glob_resources
    cls(path) for path in sublime.find_resources('')
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 200, in <listcomp>
    if match(path)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\_util\glob.py", line 42, in <lambda>
    return lambda s: (expr.search(s) is not None)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 32: invalid start byte

**Comment by rchl** [comment]
That would mean that one of the files returned by `sublime.find_resources('')` has some weird (utf-8 invalid) characters.

The list would likely be huge but if you don't mind pasting it somewhere then we would most likely find the faulty file.
Or you can just look at the list yourself and try to find anything with a weird looking characters in it.

@Thom1729 @FichteFoll

**Comment by Thom1729** [comment]
That sounds probably correct.

It looks like the error is being raised from `expr.search(s)`. But it's not clear to me exactly how this is happening. Both the regexp and the string should be of `str` type, and I'm not sure how you get a malformed value of `str` type. What follows is speculation.

I *think* that Windows file paths are encoded in [WTF-16](https://simonsapin.github.io/wtf-8/#wtf-16) (that is, they may contain unpaired surrogates, making them ill-formed UTF-16). `sublime.find_resources()` provides UTF-8 strings — at least in theory. But maybe when Sublime internally transcodes UTF-16 paths to UTF-8, it transcodes ill-formed UTF-16 to ill-formed UTF-8, and nothing explicitly checks until `expr.search(s)` runs and blows up.

*If* this is the case, then I would argue that this is a Sublime bug. Sublime should not be returning resource names that are ill-formed UTF-8. Probably it should ignore resources whose names cannot be encoded in UTF-8. We could also potentially address in `sublime_lib`. I'd have to think about the best way to do it — if we decide to handle ill-formed resource paths, we'd want to do it in some kind of systematic way.

I'll have to boot into Windows and do some experimentation.

**Comment by Thom1729** [comment]
Further experimentation has established that Windows is awful and I hate it. (I couldn't figure out how to create a file with an ill-formed UTF-16 filename.) I'll try again later or tomorrow.

**Comment by Thom1729** [comment]
@jingyuexing Can you hit me up on Discord? (I'm Thom1729 there.) I think this might be easier to work through interactively. I'm at UTC-5.

**Comment by rwols** [comment]
@jingyuexing please join the lsp channel on the Discord server for more help: https://discord.com/invite/TZ5WN8t

You may find @Thom1729 there as well. I'll close this issue now.
