### ISSUE TITLE
phantom.css is missing

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#1603]
Self explaining...

```
Traceback (most recent call last):
  File "C:\Apps\Sublime Text 40xx\Lib\python33\sublime_plugin.py", line 400, in load_module
    m.plugin_loaded()
  File "C:\Apps\Sublime Text 40xx\Data\Installed Packages\LSP.sublime-package\boot.py", line 154, in plugin_loaded
    load_css()
  File "C:\Apps\Sublime Text 40xx\Data\Installed Packages\LSP.sublime-package\plugin/core/css.py", line 21, in load
    _css = CSS()
  File "C:\Apps\Sublime Text 40xx\Data\Installed Packages\LSP.sublime-package\plugin/core/css.py", line 11, in __init__
    self.phantoms = sublime.load_resource("Packages/LSP/phantoms.css")
  File "C:\Apps\Sublime Text 40xx\Lib\python33\sublime.py", line 370, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/LSP/phantoms.css" not found
```

**Comment by rwols** [comment]
Does a restart of ST help?

How would one prevent this?

**Comment by deathaxe** [comment]
Just see the reason. Just posted it as I hat the impression of having seen it recently, but haven't investigated any further.

How to prevent it? Probably by https://github.com/SublimeText/AFileIcon/blob/2d13c1425ec32a4513477179fa59f669a5216091/plugin.py#L8-L16

Since using those lines I see far less issues with regards to reloaded modules. Even with global variables changing.

**Comment by rwols** [comment]
There was some code reloading modules previously, but was removed because it was thought it actually caused import errors: https://github.com/sublimelsp/LSP/issues/1543

There's also the problem of resources shutting down asynchronously while there's no way to communicate to ST at what point that shutdown sequence is done. So you'd see those resources suddenly have no `globals()` available to them in the async thread. Oh well, someday we'll get it right I guess :)

**Comment by deathaxe** [comment]
Maybe this is what I saw, too. Just filed the issue because I saw exceptions multiple times after restarting ST. May be unrelated though. I can't go into depth with it atm.
