### ISSUE TITLE
Errno 13 - Permission denied when starting custom language server

### ISSUE THREAD

**Issue by skerit** [sublimelsp/LSP#1624]
**Describe the bug**

I'm trying to write my own language server, and I'm having problems just getting the basic server to start from within Sublime.

**To Reproduce**

1. Write a language server in node
2. Add it to the LSP settings
3. Restart sublime
4. Get error

**Expected behavior**

It should start the server.
Manually starting the server does work without any problem.

**Screenshots**

```
Unable to start langserver
Traceback (most recent call last):
  File "/home/skerit/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 332, in start_async
    transport = create_transport(transport_config, cwd, session)
  File "/home/skerit/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 207, in create_transport
    process = start_subprocess()
  File "/home/skerit/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 196, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "/home/skerit/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 277, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

**Environment (please complete the following information):**
- OS: Manjaro 20.2.1
- Sublime Text version: 4090
- LSP version: 1.2.12
- Language servers used: intelephense

**Additional context**

```json
{
	"clients":
	{
		"langserver": {
			"command": ["/mnt/pom/develry/js-lsp/cli.js", "--stdio"],
			"enabled": true,
			"languageId": "javascript",
			"syntaxes": ["Packages/JavaScript/JavaScript.sublime-syntax"],
			"scopes": ["source.javascript"],
		}
	}
}

```

**Comment by rchl** [comment]
Include `node` binary in the command. If you don't have it in your path then use full filesystem path.
```
"command": ["node", "/mnt/pom/develry/js-lsp/cli.js", "--stdio"],
```

**Comment by skerit** [comment]
That did it! Thanks
