### ISSUE TITLE
LSP can not start 

### ISSUE THREAD

**Issue by husanjun** [sublimelsp/LSP#1656]
**Describe the bug**
```
Failed to register plugin ""
Traceback (most recent call last):
  File "F:\Sublime Text\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 641, in _register_plugin_impl
    if client_configs.add_external_config(name, settings, base_file, notify_listener):
  File "F:\Sublime Text\Data\Installed Packages\LSP.sublime-package\plugin/core/settings.py", line 37, in add_external_config
    config = ClientConfig.from_sublime_settings(name, s, file)
  File "F:\Sublime Text\Data\Installed Packages\LSP.sublime-package\plugin/core/types.py", line 564, in from_sublime_settings
    base = sublime.decode_value(sublime.load_resource(file))
  File "F:\Sublime Text\Lib\python33\sublime.py", line 435, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages//.sublime-settings" not found
```

**Environment (please complete the following information):**
- OS: win7
- Sublime Text version: 4104
- LSP version: 1.3.0
- Language servers used: [e.g. clangd, gopls, dart, Vetur, intelephense, HIE]

**Comment by rchl** [comment]
Something wrong in your LSP.sublime-settings possibly. Feel free to post it.

**Comment by husanjun** [comment]
All packages are reporting errors that seem to be a dependency problem

```
reloading python 3.3 plugin LSP-json.plugin
Traceback (most recent call last):
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\Sublime Text\Data\Installed Packages\LSP-json.sublime-package\plugin.py", line 5, in <module>
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\__init__.py", line 10, in <module>
    from .region_manager import RegionManager  # noqa: F401
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\region_manager.py", line 3, in <module>
    from ._compat.typing import Optional, List, TypeVar, Collection
ImportError: cannot import name Collection
reloading python 3.3 plugin LSP-pyls.plugin
Traceback (most recent call last):
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\Sublime Text\Data\Installed Packages\LSP-pyls.sublime-package\plugin.py", line 2, in <module>
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\__init__.py", line 10, in <module>
    from .region_manager import RegionManager  # noqa: F401
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\region_manager.py", line 3, in <module>
    from ._compat.typing import Optional, List, TypeVar, Collection
ImportError: cannot import name Collection
reloading python 3.3 plugin LSP-typescript.plugin
Traceback (most recent call last):
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "F:\Sublime Text\Data\Installed Packages\LSP-typescript.sublime-package\plugin.py", line 7, in <module>
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\__init__.py", line 8, in <module>
    from .npm_client_handler import NpmClientHandler
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 2, in <module>
    from .server_npm_resource import ServerNpmResource
  File "F:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 8, in <module>
    from sublime_lib import ResourcePath
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\__init__.py", line 10, in <module>
    from .region_manager import RegionManager  # noqa: F401
  File "F:\SUBLIM~2\Data\Packages\SUBLIM~1\st3\sublime_lib\region_manager.py", line 3, in <module>
    from ._compat.typing import Optional, List, TypeVar, Collection
ImportError: cannot import name Collection
```

**Comment by husanjun** [comment]
I noticed that `sublime_lib` has just been upgraded, I don't know if that's why

**Comment by rchl** [comment]
Not sure. It works here with the latest `sublime_lib` version.
But I'm on Mac.

**Comment by jfcherng** [comment]
It failed on my side too after I manually update `sublime_lib` to https://github.com/SublimeText/sublime_lib/releases/tag/v1.5.1

**Comment by husanjun** [comment]
I looked at the source code for `sublime_lib`
![image](https://user-images.githubusercontent.com/49985266/117408951-344c0900-af43-11eb-811e-504bd499892b.png)

I deleted the local dependency `typing`, LSP worked normally, but after restarting ST, `typing` was installed automatically, and the problem appeared again

**Comment by rchl** [comment]
The `typing` dependency must come from some other package and that is probably the main reason why it breaks.

**Comment by jfcherng** [comment]
> The `typing` dependency must come from some other package and that is probably the main reason why it breaks.

Yes, there is no `Collection` in `typing` with py33... hence the error.
```
Python 3.3>>> import typing
Python 3.3>>> dir(typing)
['AbstractSet', 'Any', 'AnyStr', 'BinaryIO', 'ByteString', 'CT_co', 'Callable', 'CallableMeta', 'ChainMap', 'ClassVar', 'Container', 'ContextManager', 'Counter', 'DefaultDict', 'Deque', 'Dict', 'FrozenSet', 'Generator', 'Generic', 'GenericMeta', 'Hashable', 'IO', 'ItemsView', 'Iterable', 'Iterator', 'KT', 'KeysView', 'List', 'Mapping', 'MappingView', 'Match', 'MethodDescriptorType', 'MethodWrapperType', 'MutableMapping', 'MutableSequence', 'MutableSet', 'NamedTuple', 'NamedTupleMeta', 'NewType', 'NoReturn', 'Optional', 'Pattern', 'Reversible', 'Sequence', 'Set', 'Sized', 'SupportsAbs', 'SupportsBytes', 'SupportsComplex', 'SupportsFloat', 'SupportsIndex', 'SupportsInt', 'SupportsRound', 'T', 'TYPE_CHECKING', 'T_co', 'T_contra', 'Text', 'TextIO', 'Tuple', 'TupleMeta', 'Type', 'TypeVar', 'TypingMeta', 'Union', 'VT', 'VT_co', 'V_co', 'ValuesView', 'WrapperDescriptorType', '_Any', '_ClassVar', '_FinalTypingBase', '_ForwardRef', '_G_base', '_NoReturn', '_Optional', '_PY36', '_Protocol', '_ProtocolMeta', '_TypeAlias', '_TypingBase', '_TypingEllipsis', '_TypingEmpty', '_Union', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__initializing__', '__loader__', '__name__', '__package__', '_allowed_types', '_check_generic', '_cleanups', '_eval_type', '_generic_new', '_get_defaults', '_get_type_vars', '_make_nmtuple', '_make_subclasshook', '_next_in_mro', '_no_slots_copy', '_overload_dummy', '_prohibited', '_qualname', '_remove_dups_flatten', '_replace_arg', '_special', '_subs_tree', '_tp_cache', '_trim_name', '_type_check', '_type_repr', '_type_vars', 'abc', 'abstractmethod', 'abstractproperty', 'cast', 'collections', 'collections_abc', 'contextlib', 'functools', 'get_type_hints', 'io', 'no_type_check', 'no_type_check_decorator', 'overload', 're', 'stdlib_re', 'sys', 'types']
```

**Comment by rwols** [comment]
What is `typing.__file__` ?

**Comment by jfcherng** [comment]
> What is `typing.__file__` ?

```
Python 3.3>>> typing.__file__
'C:\\Users\\jfcherng\\AppData\\Roaming\\SUBLIM~2\\Packages\\typing\\st3\\typing.py'
```

**Comment by jwortmann** [comment]
> 
> 
> The `typing` dependency must come from some other package and that is probably the main reason why it breaks.

Does that mean LSP doesn't work if users have any other package installed which use the `typing` dependency?

By the way, why does LSP come with its own "implementation" of typing, instead of using the dependency from Package Control?

**Comment by husanjun** [comment]
> Does that mean LSP doesn't work if users have any other package installed which use the `typing` dependency?

Stay `sublime_lib` v1.5.0 it is also working

**Comment by rwols** [comment]
> why does LSP come with its own "implementation" of typing, instead of using the dependency from Package Control?

Mypy types were first used on August 27, 2017: 875f54c0617a56e5aefe0cd6682684ad3c110f87

The first commit of the PC typing module was in 2018: https://github.com/packagecontrol/typing/commit/0849c8c17f6dec497cf342964b50d5debc5f9ddc

The plugin/core/typing.py file was first created at the beginning of 2020: 9a009d650ed66472522d71a6c876b5248fda649e

LSP could perhaps make use of the PC typing module, but I think we can skip that step once we have migrated to python 3.8: https://github.com/sublimelsp/LSP/issues/1389
