### ISSUE TITLE
An error popup occurred while upgrading LSP-pylsp

### ISSUE THREAD

**Issue by husanjun** [sublimelsp/LSP#1720]
**Describe the bug**
Hi, 
The console error is as follows:
```
reloading settings Packages/LSP-pylsp/LSP-pylsp.sublime-settings
unloading python 3.3 plugin LSP-pylsp.plugin
Traceback (most recent call last):
  File "F:\Sublime Text\Lib\python33\sublime_plugin.py", line 243, in unload_module
    module.plugin_unloaded()
  File "F:\Sublime Text\Data\Installed Packages\LSP-pylsp.sublime-package\plugin.py", line 32, in plugin_unloaded
    Pylsp.cleanup()
  File "F:\SUBLIM~3\Data\Packages\LSP_UT~1\st3\lsp_utils\generic_client_handler.py", line 44, in cleanup
    shutil.rmtree(cls.package_storage())
  File "./python3.3/shutil.py", line 478, in rmtree
  File "./python3.3/shutil.py", line 368, in _rmtree_unsafe
  File "./python3.3/shutil.py", line 368, in _rmtree_unsafe
  File "./python3.3/shutil.py", line 373, in _rmtree_unsafe
  File "./python3.3/shutil.py", line 371, in _rmtree_unsafe
PermissionError: [WinError 5] Permission denied: 'F:\\Sublime Text\\Data\\Package Storage\\LSP-pylsp\\Lib\\site-packages\\8c8c5116bc4884237d33__mypyc.cp37-win_amd64.pyd'
Package Control: Upgraded LSP-pylsp to 2.0.3
reloading settings Packages/LSP-pylsp/LSP-pylsp.sublime-settings
reloading python 3.3 plugin LSP-pylsp.plugin
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Unable to start subprocess for pylsp
Traceback (most recent call last):
  File "F:\Sublime Text\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 307, in start_async
    additional_variables = plugin_class.additional_variables()
  File "F:\SUBLIM~3\Data\Packages\LSP_UT~1\st3\lsp_utils\_client_handler\abstract_plugin.py", line 95, in additional_variables
    return cls.get_additional_variables()
  File "F:\Sublime Text\Data\Installed Packages\LSP-pylsp.sublime-package\plugin.py", line 21, in get_additional_variables
    "sublime_py_files_dir": os.path.dirname(sublime.__file__),
AttributeError: 'NoneType' object has no attribute 'path'
```

**Environment (please complete the following information):**
- OS: win7
- Sublime Text version: 4106
- LSP version: v1.4.0

**Comment by rchl** [comment]
It's it broken permanently now, even after st restart?

The issue with the files being locked on Windows, preventing then from being deleted, is likely unfixable with the current ST API.

**Comment by husanjun** [comment]
> It's it broken permanently now, even after st restart?
> 
> The issue with the files being locked on Windows, preventing then from being deleted, is likely unfixable with the current ST API.

It works after  st restart, but `Package Storage` dir  doesn't seem to have been updated

**Comment by husanjun** [comment]
Whether can modify permissions to force deletion

**Comment by rchl** [comment]
I guess removing the folder while ST is closed would be the most reliable way to fix it

**Comment by rchl** [comment]
It's not about permissions. The files are locked by Windows due to being used. This is not an issue on other operating systems.

**Comment by husanjun** [comment]
> I guess removing the folder while ST is closed would be the most reliable way to fix it / update server

This does not solve the popup box error
What do you think about updating instead of deleting?

**Comment by rchl** [comment]
You can't either update or delete locked files.

**Comment by husanjun** [comment]
Duplicate of #1456
