### ISSUE TITLE
`os.path.relpath` may throw an exception on Windows.

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP#1731]
`os.path.relpath` may throw an exception on Windows.

```
Traceback (most recent call last):
File "C:\tools\sublime\Data\Installed Packages\LSP.sublime-package\plugin/references.py", line 55, in 
File "C:\tools\sublime\Data\Installed Packages\LSP.sublime-package\plugin/references.py", line 62, in _handle_response
File "C:\tools\sublime\Data\Installed Packages\LSP.sublime-package\plugin/references.py", line 85, in _show_references_in_output_panel
File "C:\tools\sublime\Data\Installed Packages\LSP.sublime-package\plugin/references.py", line 107, in _get_relative_path
File "./python3.3/ntpath.py", line 564, in relpath
ValueError: path is on mount 'C:', start on mount '\myserver\myshare'
```

**Comment by rchl** [comment]
> On Windows, ValueError is raised when path and start are on different drives.
https://docs.python.org/3/library/os.path.html#os.path.relpath
