### ISSUE TITLE
LSP 1.13 does not start in Sublime Text 4122

### ISSUE THREAD

**Issue by eproxus** [sublimelsp/LSP#1889]
**Describe the bug**
LSP does not start.

**To Reproduce**
1. Install latest LSP version (v1.13.0) on Sublime Text 4122
2. Check console

**Expected behavior**
No errors and LSP starts.

**Console Log**
```
...
reloading settings Packages/LSP/language-ids.sublime-settings
reloading settings Packages/LSP/LSP.sublime-settings
reloading python 3.3 plugin LSP.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/boot.py", line 38, in <module>
ImportError: cannot import name LspSignatureHelpNavigateCommand
```

**Environment (please complete the following information):**
- OS: macOS 11.6
- Sublime Text version: 4122
- LSP version: v1.13.0
- Language servers used: Fails with both none and `["erlang-ls", "diagnostic-ls"]`

**Additional context**
Tested with empty LSP config just in case, same boot error.

**Comment by rchl** [comment]
Just restart ST.
