### ISSUE TITLE
LSP package stopped working after update to sublime text 4126

### ISSUE THREAD

**Issue by imihajlow** [sublimelsp/LSP#1920]
**Description**

Exception in console when configuration is reloaded:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1112, in on_load_project_async
    run_window_callbacks('on_load_project_async', window_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 721, in run_window_callbacks
    callback(w, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/boot.py", line 190, in on_load_project_async
    windows.lookup(w).on_load_project_async()
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 564, in lookup
    window_configs = self._configs.for_window(window)
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 17, in for_window
    window_configs = WindowConfigManager(window, self._configs)
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 33, in __init__
    self.update()
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/configurations.py", line 75, in update
    self.all[name] = ClientConfig.from_dict(name, c)
  File "/Users/ivan/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 700, in from_dict
    disabled_capabilities = d.get("disabled_capabilities")
AttributeError: 'int' object has no attribute 'get'
```

**To Reproduce**

In the project settings:

```
	"settings":
	{
		"LSP":
		{
			"rust-analyzer":
			{
				"enabled": true
			},
			"show_diagnostics_panel_on_save": 0
		}
	},
```

LSP.sublime-settings:

```
{
    "show_diagnostics_severity_level": 0,
    "show_diagnostics_panel_on_save": 0,
}
```

**Environment:**
- OS: macOs 12.1
- Sublime Text version: 4126
- LSP version: 1.14.0
- Language servers used: rust-analyzer

**Comment by rchl** [comment]
`show_diagnostics_panel_on_save` can only be set from LSP settings. You've put it at a place in project settings where client objects are expected.

See some related info at https://lsp.sublimetext.io/guides/client_configuration/#per-project-overrides
