### ISSUE TITLE
IndexError crash with typescript files

### ISSUE THREAD

**Issue by jacargentina** [sublimelsp/LSP#1931]
**Describe the bug**
Getting IndexError when hovering with the cursor

**To Reproduce**
Hover the desired word and wait a second

**Expected behavior**
Get the suggestions panel

**Screenshots**
```Traceback (most recent call last):
  File "/Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 449, in _update_panel_main_thread
    panel.run_command("lsp_update_panel", {"characters": characters})
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1336, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1490, in run_
    self.view.end_edit(edit)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1297, in end_edit
    sublime_api.view_end_edit(self.view_id, edit.edit_token)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 932, in on_selection_modified
    run_view_callbacks('on_selection_modified', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 152, in profiler
    return event_handler(*args)
  File "/Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/Show Character Code.sublime-package/show_char_code.py", line 7, in on_selection_modified
    self.show_char_code(view)
  File "/Users/javiercastro/Library/Application Support/Sublime Text 3/Installed Packages/Show Character Code.sublime-package/show_char_code.py", line 13, in show_char_code
    selected = view.substr(view.sel()[0].a)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1044, in __getitem__
    raise IndexError()
IndexError
```
(sublime console)

**Environment (please complete the following information):**
- OS: macOS
- Sublime Text version: 4126
- LSP version: 1.15.0
- Language servers used: LSP-typescript

**Additional context**
default configuration

**Comment by rchl** [comment]
It's the `Show Character Code` package that crashes due to not verifying that there exists a selection before working with it.

**Comment by rwols** [comment]
Fix is at https://github.com/borislubimov/ShowCharacterCode/pull/4

**Comment by rwols** [comment]
I made a pull request to fix ShowCharacterCode.

You could also write your own python plugin for the same functionality, it's not that much code.

I think we did all we can do here.
