### ISSUE TITLE
Exception: Version requirement failed. Expected >14, got 14.21.0.

### ISSUE THREAD

**Issue by ratijas** [sublimelsp/LSP#2131]
**Describe the bug**

Pyright LSP server fails to start due to error in LSP package (lsp_utils module):

**To Reproduce**
1. Open Sublime Text
2. Install LSP & PyRight plugins
3. Open random python file

**Expected behavior**
Should work

**Environment (please complete the following information):**
- OS: Arch Linux, freshly upgraded
- Sublime Text version: 4141
- LSP version: v1.20.0
- Language servers used: pyright

**Additional context**

Logs:

```
Unable to start subprocess for LSP-pyright
Traceback (most recent call last):
  File "/home/ratijas/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 251, in start_async
    if plugin_class.needs_update_or_installation():
  File "/home/ratijas/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "/home/ratijas/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 130, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "/home/ratijas/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 34, in create
    node_runtime = NodeRuntime.get(package_name, storage_path, required_node_version)
  File "/home/ratijas/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/node_runtime.py", line 48, in get
    cls._node_runtime.check_satisfies_version(required_semantic_version)
  File "/home/ratijas/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/node_runtime.py", line 144, in check_satisfies_version
    'Version requirement failed. Expected {}, got {}.'.format(required_node_version, node_version))
Exception: Version requirement failed. Expected >14, got 14.21.0.

reloading settings Packages/User/LSP-pyright.sublime-settings
reloading settings Packages/User/LSP-pyright.sublime-settings
```

**Comment by jfcherng** [comment]
Sorry. Fixed in the next version, which has been just released and will be available within hours.
