### ISSUE TITLE
打开一个lua项目时，lsp-lua提示错误，然后不断重新加载lsp-lua，导致后台存在多个lua-language-server.exe进程

### ISSUE THREAD

**Issue by matresnan** [sublimelsp/LSP#2278]
failed to register session LSP-lua to listener ViewListener(13)
Traceback (most recent call last):
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 183, in _publish_sessions_to_listener_async
    listener.on_session_initialized_async(session)
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/documents.py", line 211, in on_session_initialized_async
    self._session_views[session.config.name] = SessionView(self, session, self._uri)
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 54, in __init__
    session_buffer = SessionBuffer(self, buffer_id, uri)
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_buffer.py", line 149, in __init__
    self._check_did_open(view)
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_buffer.py", line 174, in _check_did_open
    self.do_document_diagnostic_async(view, version)
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_buffer.py", line 460, in do_document_diagnostic_async
    if mgr.should_ignore_diagnostics(self.last_known_uri, self.session.config):
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 364, in should_ignore_diagnostics
    if self._workspace.includes_excluded_path(path):
  File "C:\Users\matresnan\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/workspace.py", line 107, in includes_excluded_path
    exclude_patterns = self._folders_exclude_patterns[i]
IndexError: list index out of range

**Comment by jfcherng** [comment]
may have been fixed by https://github.com/sublimelsp/LSP/pull/2276

**Comment by rchl** [comment]
Yes, it does loke like it.

**Comment by Sevans711** [comment]
I think there is still an issue. I just removed LSP and LSP-copilot using Package Control, then reinstalled both of them. I get this error (similar as to what I was getting before this change. However now the ViewListener number is different.

```
failed to register session LSP-copilot to listener ViewListener(32)
Traceback (most recent call last):
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 183, in _publish_sessions_to_listener_async
    listener.on_session_initialized_async(session)
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/documents.py", line 211, in on_session_initialized_async
    self._session_views[session.config.name] = SessionView(self, session, self._uri)
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_view.py", line 54, in __init__
    session_buffer = SessionBuffer(self, buffer_id, uri)
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 149, in __init__
    self._check_did_open(view)
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 174, in _check_did_open
    self.do_document_diagnostic_async(view, version)
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 460, in do_document_diagnostic_async
    if mgr.should_ignore_diagnostics(self.last_known_uri, self.session.config):
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 364, in should_ignore_diagnostics
    if self._workspace.includes_excluded_path(path):
  File "/Users/Sevans/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/workspace.py", line 107, in includes_excluded_path
    exclude_patterns = self._folders_exclude_patterns[i]
IndexError: list index out of range
```

**Comment by jfcherng** [comment]
> I think there is still an issue. I just removed LSP and LSP-copilot using Package Control, then reinstalled both of them. I get this error (similar as to what I was getting before this change. However now the ViewListener number is different.

The fix is not released yet. Since you didn't mention you are using the latest master branch of LSP, I assume you weren't.

**Comment by Sevans711** [comment]
Oh, I didn't realize that, thank you for clarifying. I will either try to use the latest master branch, or wait for the release!
