### ISSUE TITLE
AttributeError: 'int' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jakitliang** [sublimelsp/LSP#2326]
**Describe the bug**
LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

**To Reproduce**
1. Install `LSP-lua`
2. restart sublime
3. Lot of err comes

**Expected behavior**
No err spawn

**Screenshots**
```
Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'

Error handling notification
Traceback (most recent call last):
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2245, in on_payload
    handler(result)
  File "C:\Users\jakit\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 2031, in m___progress
    if token.startswith(_PARTIAL_RESULT_PROGRESS_PREFIX):
AttributeError: 'int' object has no attribute 'startswith'
```

**Environment (please complete the following information):**
- OS: Windows 11 22h2
- Sublime Text version: latest
- LSP version: latest from packagecontrol
- Language servers used: lua

**Comment by suiyuex** [comment]
Issue should close until patch released.

**Comment by jfcherng** [comment]
> I think issue should open until patch released. It makes people misunderstand.

Sure people can re-open it but that's just not how GitHub auto works.
