### ISSUE TITLE
LemMinX causes KeyError

### ISSUE THREAD

**Issue by deathaxe** [sublimelsp/LSP#2331]
**Describe the bug**

Running LemMinX causes the following tracebacks to be printed to ST's console.

```
Error handling request
Traceback (most recent call last):
  File "Packages\LSP\plugin\core\sessions.py", line 2273, in on_payload
    handler(result, req_id)
  File "Packages\LSP\plugin\core\sessions.py", line 1983, in m_client_unregisterCapability
    unregistrations = params["unregisterations"]  # typo in the official specification
KeyError: 'unregisterations'
```

An `print(params)` reveals empty parameters to be sent, so my hunch is LemMinX sending a malformed request. Does it make sense to silence it, maybe by catching `KeyError`?

**LSP Log**

<details>

```
:: [14:29:44.608]  -> LemMinX textDocument/didOpen: {'textDocument': {'uri': 'file:///<augmented>/Project1/TiaExport.csproj', 'languageId': 'xml', 'version': 0, 'text': '...'}}
:: [14:29:44.640] <-- LemMinX client/registerCapability (1): {'registrations': [{'id': 'b2ffd09b-f82c-4f0e-b305-2c4d32006003', 'method': 'textDocument/codeAction', 'registerOptions': {'resolveProvider': True}}]}
:: [14:29:44.640] >>> LemMinX (1) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (2): {'registrations': [{'id': '13a3e13c-7d89-4ae3-99e7-c349edfbb25f', 'method': 'textDocument/completion', 'registerOptions': {'resolveProvider': True, 'triggerCharacters': ['.', ':', '<', '"', '=', '/', '\\', '?', "'", '&', '#']}}]}
:: [14:29:44.640] >>> LemMinX (2) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (3): {'registrations': [{'id': '32a3675f-d2fc-4895-9181-16ec87e09543', 'method': 'textDocument/documentHighlight'}]}
:: [14:29:44.640] >>> LemMinX (3) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (4): {'registrations': [{'id': 'c3e48709-c22c-4710-8dd5-004ce5fccd1a', 'method': 'textDocument/foldingRange'}]}
:: [14:29:44.640] >>> LemMinX (4) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (5): {'registrations': [{'id': 'c164c0f5-75f7-4b14-864d-d6835725fb5e', 'method': 'textDocument/hover'}]}
:: [14:29:44.640] >>> LemMinX (5) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (6): {'registrations': [{'id': 'd6dc916c-1650-4735-89c0-c881079edcbf', 'method': 'textDocument/documentLink', 'registerOptions': {'resolveProvider': True}}]}
:: [14:29:44.640] >>> LemMinX (6) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (7): {'registrations': [{'id': '7f7c3e8e-54c8-44d1-8a28-f5587a73d3e2', 'method': 'textDocument/documentColor', 'registerOptions': {}}]}
:: [14:29:44.640] >>> LemMinX (7) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (8): {'registrations': [{'id': 'b1ab6cc0-234c-4ff5-8d5a-065f995fb5ba', 'method': 'textDocument/rename', 'registerOptions': {'prepareProvider': True}}]}
:: [14:29:44.640] >>> LemMinX (8) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (9): {'registrations': [{'id': '7edb7b05-f252-44b7-8972-8b2d1b65b484', 'method': 'textDocument/definition'}]}
:: [14:29:44.640] >>> LemMinX (9) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (10): {'registrations': [{'id': 'a4d1e8c2-e1c0-41f6-8976-2c77cff08317', 'method': 'textDocument/typeDefinition'}]}
:: [14:29:44.640] >>> LemMinX (10) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (11): {'registrations': [{'id': '5c82adb4-59cb-4fc6-b3ba-7ba26b65d021', 'method': 'textDocument/references'}]}
:: [14:29:44.640] >>> LemMinX (11) (duration: 0ms): None
:: [14:29:44.640] <-- LemMinX client/registerCapability (12): {'registrations': [{'id': 'ed6389fc-c385-4223-ae6c-4396721eafae', 'method': 'textDocument/formatting'}]}
:: [14:29:44.642] >>> LemMinX (12) (duration: 0ms): None
:: [14:29:44.642] <-- LemMinX client/registerCapability (13): {'registrations': [{'id': 'ad59ac08-77f5-41d7-93ba-1127805aac3d', 'method': 'textDocument/rangeFormatting'}]}
:: [14:29:44.642] >>> LemMinX (13) (duration: 0ms): None
:: [14:29:44.642] <-- LemMinX client/registerCapability (14): {'registrations': [{'id': '1d40fc97-f5c3-49d9-9f90-c9733a47b503', 'method': 'textDocument/selectionRange'}]}
:: [14:29:44.642] >>> LemMinX (14) (duration: 0ms): None
:: [14:29:44.642] <-- LemMinX client/registerCapability (15): {'registrations': [{'id': 'a8e8f24f-aeaa-4f2c-8312-8c3f11ef19b2', 'method': 'textDocument/documentSymbol'}]}
:: [14:29:44.642] >>> LemMinX (15) (duration: 0ms): None
:: [14:29:44.642] <-- LemMinX client/unregisterCapability (16): {}
:: [14:29:44.642] ~~> LemMinX (16) (duration: 0ms): {'code': -32603, 'message': "'unregisterations'"}
:: [14:29:44.643] <-- LemMinX client/registerCapability (17): {'registrations': [{'id': 'f3c6f430-eb7c-42d8-bc8a-7762ac78f429', 'method': 'workspace/executeCommand', 'registerOptions': {'commands': ['xml.check.bound.grammar', 'xml.refactor.surround.with', 'xml.associate.grammar.insert', 'xml.validation.current.file', 'xml.check.file.pattern', 'xml.validation.all.files']}}]}
:: [14:29:44.643] >>> LemMinX (17) (duration: 0ms): None
```

</details>

**To Reproduce**

1. Install LSP-LemMinX
2. Open a XML document
3. Have a look at ST's console

**Expected behavior**

Not tracebacks

**Environment (please complete the following information):**
- OS: Windows 11
- Sublime Text version: 4156
- LSP version: `main`
- Language servers used: LemMinX

**Additional context**
Add any other context about the problem here. For example, whether you're using a helper
package or your manual server configuration in LSP.sublime-settings. When using
a manual server configuration please include it here if you believe it's applicable.

**Comment by deathaxe** [comment]
I am not aware of spec details as I don't follow them anymore. Just noticed that traceback and asking for feedback. I can't judge it being malformed or not, just a hunch.

That said, changing lin 1982 to

```py
        unregistrations = params.get("unregisterations") or []  # typo in the official specification
```

would cause the empty params to be ignored silently.

**Comment by rchl** [comment]
Server initiates this

> <-- LemMinX client/unregisterCapability (16): {}

My feedback is that it's a spec violation on the server side. It's specified in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_unregisterCapability where the `unregisterations` property is not optional. It can be set to empty array though although it doesn't really make sense to send it then.

And yes, my point is that we don't want to hide spec violations with changes like the suggested one.

**Comment by deathaxe** [comment]
Shouldn't it just return a relevant error code to the server then, instead of raising a local exception?

**Comment by rchl** [comment]
Potentially yes. But then we'd need to run all the code within a try block which could also hide real issues on our side. If I'd to pick one of those two then I'd rather prefer the current behavior. But maybe there is a third option...

**Comment by rchl** [comment]
Third option could be to verify the schema of incoming requests/notifications and raise errors in that case.
