### ISSUE TITLE
Latest version breaks on startup

### ISSUE THREAD

**Issue by drcongo** [sublimelsp/LSP#2390]
**Describe the bug**
My LSP plugin updated this morning and all my LSP-x plugins have stopped working.  Opening the Sublime console I can see an error...

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1697, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/boot.py", line 10, in <module>
ImportError: cannot import name LspToggleCodeLensesCommand
```

I can't work out where the file `boot.py` is in this repo though.

**To Reproduce**
1. Open SublimeText

**Expected behavior**
LSP working

**Environment (please complete the following information):**
- OS: macOS Sonoma 14.2.1 (23C71)
- Sublime Text version: 4169
- LSP version: 4070-1.27.0
- Language servers used: ruff, copilot, css, html

**Additional context**
Nothing unusual about my setup - I've restarted Sublime several times and get the same error on boot every time.

**Comment by drcongo** [comment]
(actually, updating the ruff-lsp python package seems to have fixed it, though probably good to have this issue for anyone else finding the same issue via search)

**Comment by rchl** [comment]
There should be a big warning above the changelog that should pop up on LSP update that says to restart LSP after the package is updated. Not restarting the ST after update is the reason for this error.
