### ISSUE TITLE
`KeyError` in LSP plugin when trying to open Preferences

### ISSUE THREAD

**Issue by samirbajaj** [sublimelsp/LSP#2399]
My ST4 setup: version: 4169 osx arm64 channel: stable

LSP v1.27.0

I see this trace in the console whenever I try to open Settings/Preferences (it opens successfully, but this error worries me):

```
Unable to open /Users/samir.bajaj/Library/Application Support/Sublime Text/Packages/Default/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Users/samir.bajaj/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 968, in clear_async
  File "/Users/samir.bajaj/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/session_view.py", line 104, in on_before_remove
  File "/Users/samir.bajaj/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 203, in remove_session_view
  File "./python3.3/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x104a93ef8; to 'SessionView' at 0x104a5b7b8>
```

I originally posted this on the Sublime Forum, but got no responses.

Thank you for your help.

**Comment by rchl** [comment]
Can you record a video of you opening the preferences?

Also you can try in [safe mode](https://www.sublimetext.com/docs/safe_mode.html). It doesn't reproduce here.

**Comment by samirbajaj** [comment]
Hi @rchl -- thank you for your response.

Here's a video I recorded.

Also, I couldn't reproduce it in safe mode.

Hope this helps!

https://github.com/sublimelsp/LSP/assets/37282578/e0d1356c-f5be-4d2c-b831-f92826b9c102

**Comment by rchl** [comment]
Thanks. I can reproduce it in safe mode with just LSP and LSP-json installed.
