### ISSUE TITLE
[Runtime Error] ModuleNotFoundError: No module named 'wcmatch'

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP#2457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
```log
Traceback (most recent call last):
  File "D:\Programming Files\sublime\Lib\python38\sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP-gopls.sublime-package\boot.py", line 12, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP-gopls.sublime-package\plugin/__init__.py", line 2, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP-gopls.sublime-package\plugin/commands.py", line 9, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP-gopls.sublime-package\plugin/vulnerabilities.py", line 5, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP-gopls.sublime-package\plugin/utils.py", line 8, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/__init__.py", line 12, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 4, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 3, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/diagnostics_storage.py", line 4, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/views.py", line 39, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/settings.py", line 3, in <module>
  File "D:\Programming Files\sublime\Data\Installed Packages\LSP.sublime-package\plugin/core/types.py", line 9, in <module>
ModuleNotFoundError: No module named 'wcmatch'
```

**Environment (please complete the following information):**

- OS: windows
- Sublime Text version: 4173
- LSP version: v2.0.0
- Language servers used: ignore

**Additional context**
None

**Comment by predragnikolic** [comment]
Hello, 

This ticket is a duplicate of https://github.com/sublimelsp/LSP/issues/2454
