### ISSUE TITLE
Cannot install LSP on clean installation

### ISSUE THREAD

**Issue by istudyatuni** [sublimelsp/LSP#2479]
**Describe the bug**

Cannot install LSP

**To Reproduce**

1. Open sublime in safe mode (or temporally move old config directory)
2. Install package control
3. Install LSP
4. After completing there is no LSP

**Expected behavior**

LSP can be installed

**Logs**

<details><summary>Logs from bottom panel</summary>
<p>

```
startup, version: 4169 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
application: /opt/sublime_text
working dir: /home/[..]
packages path: /home/[..]/.config/sublime-text/Packages
state path: /home/[..]/.config/sublime-text/Local
zip path: /opt/sublime_text/Packages
zip path: /home/[..]/.config/sublime-text/Installed Packages
ignored_packages: ["Debugger", "Emmet", "LSP-bash", "LSP-file-watcher-chokidar", "Vintage"]
generating syntax summary
generating meta info summary
ignored packages updated to: ["Vintage"]
pre session restore time: 0.347643
startup time: 0.464316
first paint time: 0.503653
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'bracex' is not currently installed; installing...
Package Control: The dependency 'bracex' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'typing_extensions' is not currently installed; installing...
Package Control: The dependency 'typing_extensions' is not available
Package Control: The dependency 'typing_extensions' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

</p>
</details> 

**Environment (please complete the following information):**

- OS: Arch linux
- Sublime Text version: 4169
- LSP version: -
- Language servers used: -

**Additional context**

-

**Comment by predragnikolic** [comment]
Cannot reproduce.

----

1. Does restarting ST help? Usually a restart of Sublime Text helps.

2. From the command palette select `Preferences: Package Control` and check if LSP didn't got put in `"in_process_packages"`, if yes, remove it.

3. Check if "LSP" is put in `"ignored_packages"` in Preferences.sublime-settings.  If yes, remove it.

**Comment by jfcherng** [comment]
> Package Control: The dependency 'typing_extensions' could not be installed or updated

Not sure related or not: https://github.com/sublimelsp/LSP/blob/fc5a7c75c8cec2e6765e218f7df980315c5c9ff3/dependencies.json#L6
The canonical name for Package Control is `typing-extensions`.

**Comment by istudyatuni** [comment]
> 1. Does restarting ST help? Usually a restart of Sublime Text helps.
> 
> 2. From the command palette select `Preferences: Package Control` and check if LSP didn't got put in `"in_process_packages"`, if yes, remove it.
> 
> 3. Check if "LSP" is put in `"ignored_packages"` in Preferences.sublime-settings.  If yes, remove it.

No to all points

**Comment by predragnikolic** [comment]
I will take a closer look tonight.
But on first glance, based on the provided log,
LSP looks like it has been put to ignored packages:

```
ignored packages updated to: ["LSP", "Vintage"]
```

Try removing it from there.

**Comment by istudyatuni** [comment]
If I understand correctly, it's how package control works. Before installing it puts the package to the ignore list, and after installation removes the package from the list

**Comment by rchl** [comment]
You need to upgrade Package Control before you can use LSP (which relies on latest Package Control).

**Comment by jaraco** [comment]
Today, my editor updated to LSP 2.1.0. Afterward, LSP is no longer working and is failing and emitting a traceback:

```
Traceback (most recent call last):
  File "/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/AppTranslocation/612C39DB-7AB3-487C-9E5C-53897225F16A/d/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 432, in load_module
    m.plugin_loaded()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/boot.py", line 197, in plugin_loaded
    load_css()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/css.py", line 23, in load
    _css = CSS()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/css.py", line 7, in __init__
    self.popups = sublime.load_resource("Packages/LSP/popups.css")
  File "/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/AppTranslocation/612C39DB-7AB3-487C-9E5C-53897225F16A/d/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 1199, in load_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Packages/LSP/popups.css" not found
```

I uninstalled and reinstalled LSP, but the error remains. And I can't find an LSP folder anywhere in my settings directory.

I have the latest package control (4.0.6).

**Comment by rchl** [comment]
@jaraco your issue doesn't look related. Try https://forum.sublimetext.com/t/sublime-text-4-will-not-run-my-python-code-on-macos/69065/10

**Comment by jfcherng** [comment]
> FileNotFoundError: resource "Packages/LSP/popups.css" not found

I can reproduce this with a clean ST 4169 on my Windows machine. However, after restarting ST, LSP works.

**Comment by istudyatuni** [comment]
> The log you've provided is not from safe mode

That's was a log from clean installation (emulating with removing .config/sublime-text), but log from the safe mode is almost the same

<details><summary>safe mode</summary>
<p>

```log
startup, version: 4169 linux x64 channel: stable
SAFE MODE - overriding packages, state and cache paths
executable: /opt/sublime_text/sublime_text
application: /opt/sublime_text
working dir: /home/[..]
packages path: /home/[..]/.config/sublime-text-safe-mode/Packages
state path: /home/[..]/.config/sublime-text-safe-mode/Local
zip path: /opt/sublime_text/Packages
zip path: /home/[..]/.config/sublime-text-safe-mode/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 3.06987
startup time: 3.27725
first paint time: 3.33824
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
plugins loaded
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
Package Control: Not running package cleanup since bootstrapping is not yet complete
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["LSP", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'bracex' is not currently installed; installing...
Package Control: The dependency 'bracex' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: The dependency 'typing_extensions' is not currently installed; installing...
Package Control: The dependency 'typing_extensions' is not available
Package Control: The dependency 'typing_extensions' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

</p>
</details>

**Comment by jfcherng** [comment]
> > The log you've provided is not from safe mode
> 
> That's was a log from clean installation (emulating with removing .config/sublime-text), but log from the safe mode is almost the same
> 
> safe mode

Unfortunately, there is no way to install LSP in safe mode because LSP requires Package Control v4 and installing that requires a restart (thus safe mode won't work).

**Comment by istudyatuni** [comment]
I tried now with restarts, after a restart it installed, and after one more restart issue with popups.css disappeared, thanks!

**Comment by hhofner** [comment]
I'm having this issue, but restarting ST does not work. OS is Mac Ventura 13.4.

**Comment by rchl** [comment]
Make sure that you are using latest Package Control and that your channels are not overridden - https://github.com/sublimelsp/LSP/issues/2465#issuecomment-2085877488

**Comment by hhofner** [comment]
Okay weird, I have been trying everything found in these issues, including the #2465 comment and nothing work, even restart ST many times. And after some time it just updated Package Control and finally let me install LSP. Apologies for taking the time!
