### ISSUE TITLE
Updated to LSP 2.1.0 leads to FileNotFoundError and no LSP

### ISSUE THREAD

**Issue by jaraco** [sublimelsp/LSP#2480]
Today, my editor updated to LSP 2.1.0. Afterward, LSP is no longer working and is failing and emitting a traceback:

```
Traceback (most recent call last):
  File "/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/AppTranslocation/612C39DB-7AB3-487C-9E5C-53897225F16A/d/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 432, in load_module
    m.plugin_loaded()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/boot.py", line 197, in plugin_loaded
    load_css()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/css.py", line 23, in load
    _css = CSS()
  File "/Users/jaraco/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/css.py", line 7, in __init__
    self.popups = sublime.load_resource("Packages/LSP/popups.css")
  File "/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/AppTranslocation/612C39DB-7AB3-487C-9E5C-53897225F16A/d/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 1199, in load_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Packages/LSP/popups.css" not found
```

I uninstalled and reinstalled LSP, but the error remains. And I can't find an LSP folder anywhere in my settings directory.

I have the latest package control (4.0.6).

_Originally posted by @jaraco in https://github.com/sublimelsp/LSP/issues/2479#issuecomment-2121515667_

**Comment by jaraco** [comment]
@rchl said:

> Try https://forum.sublimetext.com/t/sublime-text-4-will-not-run-my-python-code-on-macos/69065/10

Essentially, two things to try:

> Could be an app-translocation thing. If `Sublime Text.app` is not in your _Applications_ folders I suggest moving it there using _Finder_. If it is you can move it somewhere else and then move it back.
>
> Could also be a macOS permissions issue. Under _System Preferences > Security & Privacy > Privacy > Full Disk Access_ you can try adding Sublime Text.

**Comment by LDAP** [comment]
Did you try restarting ST after the update, as suggested here: https://github.com/sublimelsp/LSP/issues/2479#issuecomment-2122548304

**Comment by jaraco** [comment]
> Did you try restarting ST after the update, as suggested here: [#2479 (comment)](https://github.com/sublimelsp/LSP/issues/2479#issuecomment-2122548304)

I had tried restarting ST, but the problem persisted.

**Comment by joshmfrankel** [comment]
Have tried moving the app out of `/Applications` to another folder and back. Have also set permissions for Full Disk Access. I'm still receiving the `FileNotFoundError: resource "Packages/LSP/popups.css" not found`.

**Comment by rchl** [comment]
Does the error message refer to `AppTranslocation` like the original comment in here? If so then you need to fix that by trying previously mentioned methods.
