### ISSUE TITLE
LSP.plugin.inlay_hint.LspToggleInlayHintsCommand init failure

### ISSUE THREAD

**Issue by mooh-pooh** [sublimelsp/LSP#2569]
Sublime-LSP fails to init inlay hints on startup

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 535, in create_window_commands
    o = cls(window)
  File "C:\Users\user\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/inlay_hint.py", line 24, in __init__
    window.settings().set('lsp_show_inlay_hints', userprefs().show_inlay_hints)
AttributeError: 'NoneType' object has no attribute 'show_inlay_hints'

The above exception was the direct cause of the following exception:

RuntimeError: unable to instantiate 'LSP.plugin.inlay_hint.LspToggleInlayHintsCommand'

```
- OS: Win10
- Sublime Text version: 4180
- LSP version: 2.3.0

Re-install does not help, reproducible on every startup.

**Comment by jwortmann** [comment]
I've never seen this error, but it looks like this is some kind of timing bug. The error seems to be that `userprefs()` is None.

Note that `userprefs()` returns the `_settings` variable, which gets initialized in `plugin_loaded`:
https://github.com/sublimelsp/LSP/blob/8b7afad0527400e113dd6cd0f1f63175bcc599c7/boot.py#L195-L196
https://github.com/sublimelsp/LSP/blob/8b7afad0527400e113dd6cd0f1f63175bcc599c7/plugin/core/settings.py#L159

So probably we shouldn't use `userprefs()` from the `__init__` method of a command?
