### ISSUE TITLE
Python server does not start: pyls

### ISSUE THREAD

**Issue by RafalSkolasinski** [sublimelsp/LSP#884]
### OS and language server
Ubuntu and pyls
### How you installed LSP (Package Control or from git?)
Package Control
### Minimal reproduction steps
```
pip3 install --user python-language-server
```
and open folder with python code

pyls - is in PATH
### Log
```
pyls for /home/rskolasinski/work/seldon-core/python did not initialize properly. Disabling until this window is restarted
Traceback (most recent call last):
  File "/home/rskolasinski/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 334, in get_session
    return self._find_session(config_name, file_path)
  File "/home/rskolasinski/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 344, in _find_session
    if session.handles_path(file_path):
  File "/home/rskolasinski/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 200, in handles_path
    with self.acquire_timeout():
  File "./python3.3/contextlib.py", line 48, in __enter__
  File "/home/rskolasinski/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 193, in acquire_timeout
    raise InitializeError(self)
LSP.plugin.core.sessions.InitializeError: pyls did not respond to the initialize request within 3 seconds
```

**Comment by RafalSkolasinski** [comment]
Hmm... I don't understand how but it is working now.
Will reopen if issue come back.
