### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by davidben** [sublimelsp/LSP#890]
When I use LSP (0.9.5 installed via Package Control) with `clangd`, I get the following error working on Chromium:

```
Error handling server payload
Traceback (most recent call last):
  File "[...]/LSP.sublime-package/plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "[...]/LSP.sublime-package/plugin/core/rpc.py", line 224, in response_handler
    handler(result)
  File "[...]/LSP.sublime-package/plugin/core/sessions.py", line 273, in _handle_initialize_result
    self._on_post_initialize(self, None)
  File "[...]/LSP.sublime-package/plugin/core/windows.py", line 580, in _handle_post_initialize
    self.documents.add_session(session)
  File "[...]/LSP.sublime-package/plugin/core/windows.py", line 117, in add_session
    self._notify_open_documents(session)
  File "[...]/LSP.sublime-package/plugin/core/windows.py", line 151, in _notify_open_documents
    for file_name in self._document_states:
RuntimeError: Set changed size during iteration
```

I tried enabling `log_debug` and `log_server` per https://lsp.readthedocs.io/en/latest/troubleshooting/, but that caused it to work. I'm guessing there is some race condition here.

The offending loop was added in #868. Prior to that PR, `_notify_open_documents` iterated over `list(self._document_states)`, which made a copy of the set (then a dict).

**Comment by rwols** [comment]
Thanks for pointing this out. I added back the creation of the list before iterating over it.
