### ISSUE TITLE
Improve handling of missing project folders

### ISSUE THREAD

**Issue by safield** [sublimelsp/LSP#893]
I am using LSP plugin installed on Windows 10 through package control.

When I have a project file that contains folder paths that do not exist on the file system, I get the following error, and LSP disables clangd.

This could potentially be improved. LSP could either ignore missing folders (this is what sublime text seems to do). Or LSP could give a more informative error to the user. Since LSP is reading a user edited file, something more informative than an assert should be implemented.

```
LSP: global configs ['phpls=False', 'gopls=False', 'rls=False', 'dart=False', 'cquery=False', 'metals=False', 'flow=False', 'rlang=False', 'ocaml=False', 'lsp-tsserver=False', 'clangd=False', 'typescript-language-server=False', 'javascript-typescript-langserver=False', 'elixir-ls=False', 'ra-lsp=False', 'polymer-ide=False', 'reason=False', 'bashls=False', 'ruby=False', 'intelephense-ls=False', 'vscode-css=False', 'golsp=False', 'jdtls=False', 'pyls=False', 'eslint=False', 'haskell-ide-engine=False']
LSP: window has override for clangd {'enabled': True}
LSP: window 2 starting 1 initial views
LSP: window has override for clangd {'enabled': True}
LSP: window 2 requests clangd for C:\somedir\myfile.cpp
LSP: window has override for clangd {'enabled': True}
Could not start clangd



Server will be disabled for this window
Traceback (most recent call last):
  File "C:\Users\sfield\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 471, in _start_client
    self._workspace.all(),         # workspace_folders
  File "C:\Users\sfield\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/workspace.py", line 19, in all
    return [WorkspaceFolder.from_path(f) for f in self.folders]
  File "C:\Users\sfield\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/workspace.py", line 19, in <listcomp>
    return [WorkspaceFolder.from_path(f) for f in self.folders]
  File "C:\Users\sfield\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/protocol.py", line 427, in from_path
    assert os.path.isdir(path)
AssertionError


```

**Comment by tomv564** [comment]
Yes, I would love to remove all occurrences of `assert` in favour of proper error handling where needed. Maybe it's useful while debugging but this is one example where we needlessly break the user experience.
