### ISSUE TITLE
Latest versions of plugins cause microsoft python language server to crash

### ISSUE THREAD

**Issue by desilinguist** [sublimelsp/LSP#918]
I have been using LSP for a few months now and it has worked just fine. After Package Control updated the LSP package to the latest version (0.9.7) today, `dotnet` started crashing, even after I quit Sublime Text and restarted. And even after I removed the LSP package and reinstalled.

I updated the .NET Core for macOS to the latest version but the crashes still persisted. 

I then removed the package and manually installed it via git and checked out both 0.9.6 and 0.9.5 versions. v0.9.6 still caused botnet to crash but as soon as I went to v0.9.5, things stared working again.

* OS and language server: macOS 10.14.6, Microsoft Python Language Server installed from https://github.com/microsoft/python-language-server/
* How you installed LSP (Package Control or from git?): Package Control

**Comment by rwols** [comment]
Can you provide some RPC logging? You can see the logs with `LSP: Toggle Log Panel` from the command-palette.

**Comment by rwols** [comment]
Went ahead and took a peek myself.

I installed this language server on ubuntu 19.10 as follows.

```bash
sudo snap install dotnet-sdk --classic
cd path/to/repo/src/LanguageServer/Impl
dotnet-sdk.dotnet build
```

With this client config:

```js
		"microsoft-python-language-server":
		{
			"command": ["/home/raoul/dev/microsoft-python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer"],
			"enabled": true,
			"initializationOptions": {},
			"languages": [
				{"languageId": "python", "scopes": ["source.python"], "syntaxes": ["Packages/Python/Python.sublime-syntax"]}
			],
			"env": {
				"DOTNET_ROOT": "/snap/dotnet-sdk/current"
			}
		},
```

I get this output:

```
microsoft-python-language-server: Analysis cache path: /home/raoul/.cache/Microsoft/Python Language Server
microsoft-python-language-server: Microsoft Python Language Server version 1.0.0.0
microsoft-python-language-server: Workspace root: /home/raoul/.config/sublime-text-3/Packages/LSP
:: --> microsoft-python-language-server initialize(1): {'processId': 13728, 'rootUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP', 'rootPath': '/home/raoul/.config/sublime-text-3/Packages/LSP', 'workspaceFolders': [{'name': 'LSP', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}, {'name': 'LSP-eslint', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP-eslint'}, {'name': 'metals-sublime', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/metals-sublime'}, {'name': 'tonic', 'uri': 'file:///home/raoul/Documents/Programming/tonic'}, {'name': 'User', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/User'}], 'capabilities': {'textDocument': {'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'completion': {'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'completionItem': {'snippetSupport': True}}, 'references': {}, 'synchronization': {'willSave': True, 'willSaveWaitUntil': True, 'didSave': True}, 'definition': {'linkSupport': True}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'declaration': {'linkSupport': True}, 'formatting': {}, 'publishDiagnostics': {'relatedInformation': True}, 'implementation': {'linkSupport': True}, 'typeDefinition': {'linkSupport': True}, 'documentHighlight': {}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}}, 'rangeFormatting': {}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'colorProvider': {}, 'rename': {}}, 'workspace': {'didChangeConfiguration': {}, 'workspaceFolders': True, 'configuration': True, 'executeCommand': {}, 'applyEdit': True, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}}}}
:: <<< microsoft-python-language-server 1: {'capabilities': {'codeActionProvider': {'codeActionKinds': ['quickfix', 'refactor']}, 'documentHighlightProvider': False, 'definitionProvider': True, 'hoverProvider': True, 'completionProvider': {'triggerCharacters': ['.'], 'resolveProvider': False}, 'signatureHelpProvider': {'triggerCharacters': ['(', ',', ')']}, 'renameProvider': True, 'workspaceSymbolProvider': True, 'textDocumentSync': {'willSaveWaitUntil': False, 'willSave': False, 'change': 2, 'openClose': True}, 'documentRangeFormattingProvider': False, 'referencesProvider': True, 'declarationProvider': True, 'documentOnTypeFormattingProvider': {'moreTriggerCharacter': [';', ':'], 'firstTriggerCharacter': '\n'}, 'documentSymbolProvider': True, 'documentFormattingProvider': False}}
::  -> microsoft-python-language-server initialized: {}
:: <-- microsoft-python-language-server workspace/configuration(2): {'items': [{'section': 'python', 'scopeUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}]}
:: >>> microsoft-python-language-server 2: [None]
:: <?  microsoft-python-language-server telemetry/event: {'Properties': {'name': 'InvalidOperationException', 'stackTrace': '   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.GetUserConfiguredPaths(JToken pythonSection) in /home/raoul/Documents/Programming/microsoft-python-language-server/src/LanguageServer/Impl/LanguageServer.Configuration.cs:line 174\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialized(JToken token, CancellationToken cancellationToken) in /home/raoul/Documents/Programming/microsoft-python-language-server/src/LanguageServer/Impl/LanguageServer.Lifetime.cs:line 57', 'method': 'initialized', 'plsVersion': '1.0.0.0-debug'}, 'EventName': 'python_language_server/rpc.exception', 'Measurements': {}}
::  -> microsoft-python-language-server textDocument/didOpen
microsoft-python-language-server: Process terminated. Assertion failed.
microsoft-python-language-server: at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidOpenTextDocument(JToken token, CancellationToken cancellationToken) in /home/raoul/Documents/Programming/microsoft-python-language-server/src/LanguageServer/Impl/LanguageServer.cs:line 123
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
microsoft-python-language-server: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
microsoft-python-language-server: at System.Threading.ThreadPoolWorkQueue.Dispatch()
microsoft-python-language-server: at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

It looks like the maintainers forgot to handle `null`. So I modified the client configuration by adding some settings:

```js
		"microsoft-python-language-server":
		{
			"command": ["/home/raoul/dev/microsoft-python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer"],
			"enabled": true,
			"initializationOptions": {},
			"languages": [
				{"languageId": "python", "scopes": ["source.python"], "syntaxes": ["Packages/Python/Python.sublime-syntax"]}
			],
			"env": {
				"DOTNET_ROOT": "/snap/dotnet-sdk/current"
			},
			"settings": {
				"python": {
					"analysis": {
						"errors": ["undefined-variable"],
						"warnings": ["unknown-parameter-name"],
						"information": ["unresolved-import"],
						"disabled": ["too-many-function-arguments", "parameter-missing"]
					}
				}
			}
		},
```

I get this output:

```
microsoft-python-language-server: Analysis cache path: /home/raoul/.cache/Microsoft/Python Language Server
microsoft-python-language-server: Microsoft Python Language Server version 1.0.0.0
microsoft-python-language-server: Workspace root: /home/raoul/.config/sublime-text-3/Packages/LSP
:: --> microsoft-python-language-server initialize(1): {'workspaceFolders': [{'name': 'LSP', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}, {'name': 'LSP-eslint', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP-eslint'}, {'name': 'metals-sublime', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/metals-sublime'}, {'name': 'tonic', 'uri': 'file:///home/raoul/Documents/Programming/tonic'}, {'name': 'User', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/User'}], 'processId': 14038, 'capabilities': {'textDocument': {'rangeFormatting': {}, 'colorProvider': {}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'formatting': {}, 'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'synchronization': {'willSave': True, 'willSaveWaitUntil': True, 'didSave': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'documentHighlight': {}, 'declaration': {'linkSupport': True}, 'publishDiagnostics': {'relatedInformation': True}, 'typeDefinition': {'linkSupport': True}, 'rename': {}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'implementation': {'linkSupport': True}, 'references': {}, 'definition': {'linkSupport': True}}, 'workspace': {'workspaceFolders': True, 'didChangeConfiguration': {}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'configuration': True, 'executeCommand': {}, 'applyEdit': True}}, 'rootUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP', 'rootPath': '/home/raoul/.config/sublime-text-3/Packages/LSP'}
:: <<< microsoft-python-language-server 1: {'capabilities': {'documentSymbolProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',', ')']}, 'definitionProvider': True, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'renameProvider': True, 'workspaceSymbolProvider': True, 'documentFormattingProvider': False, 'documentRangeFormattingProvider': False, 'textDocumentSync': {'openClose': True, 'change': 2, 'willSaveWaitUntil': False, 'willSave': False}, 'hoverProvider': True, 'referencesProvider': True, 'declarationProvider': True, 'codeActionProvider': {'codeActionKinds': ['quickfix', 'refactor']}, 'documentHighlightProvider': False, 'documentOnTypeFormattingProvider': {'moreTriggerCharacter': [';', ':'], 'firstTriggerCharacter': '\n'}}}
::  -> microsoft-python-language-server workspace/didChangeConfiguration: {'settings': {'python': {'analysis': {'errors': ['undefined-variable'], 'warnings': ['unknown-parameter-name'], 'disabled': ['too-many-function-arguments', 'parameter-missing'], 'information': ['unresolved-import']}}}}
::  -> microsoft-python-language-server initialized: {}
::  -> microsoft-python-language-server textDocument/didOpen
:: <-- microsoft-python-language-server workspace/configuration(2): {'items': [{'section': 'python', 'scopeUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}]}
:: >>> microsoft-python-language-server 2: [{'analysis': {'errors': ['undefined-variable'], 'warnings': ['unknown-parameter-name'], 'disabled': ['too-many-function-arguments', 'parameter-missing'], 'information': ['unresolved-import']}}]
:: <-  microsoft-python-language-server window/showMessage: {'type': 1, 'message': 'Interpreter does not exist; analysis will not be available.'}
microsoft-python-language-server: Interpreter search paths:
microsoft-python-language-server: User search paths:
microsoft-python-language-server: Unable continue, no builtins module content.
microsoft-python-language-server: Process terminated. Assertion failed.
microsoft-python-language-server: at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DidChangeConfiguration(JToken token, CancellationToken cancellationToken) in /home/raoul/Documents/Programming/microsoft-python-language-server/src/LanguageServer/Impl/LanguageServer.Configuration.cs:line 44
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
microsoft-python-language-server: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
microsoft-python-language-server: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
microsoft-python-language-server: at System.Threading.ThreadPoolWorkQueue.Dispatch()
microsoft-python-language-server: at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Now it looks like it is complaining about a missing python interpreter (to be continued)

**Comment by rwols** [comment]
Setting the interpreter path in the initializationOptions does the trick:

```
microsoft-python-language-server: Workspace root: /home/raoul/.config/sublime-text-3/Packages/LSP
:: --> microsoft-python-language-server initialize(1): {'initializationOptions': {'interpreter': {'properties': {'interpreterPath': '/usr/bin/python3', 'version': '3.7.5'}}}, 'capabilities': {'workspace': {'configuration': True, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'executeCommand': {}, 'applyEdit': True, 'workspaceFolders': True, 'didChangeConfiguration': {}}, 'textDocument': {'rename': {}, 'synchronization': {'willSave': True, 'didSave': True, 'willSaveWaitUntil': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}}, 'definition': {'linkSupport': True}, 'hover': {'contentFormat': ['markdown', 'plaintext']}, 'implementation': {'linkSupport': True}, 'documentHighlight': {}, 'rangeFormatting': {}, 'formatting': {}, 'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'references': {}, 'typeDefinition': {'linkSupport': True}, 'declaration': {'linkSupport': True}, 'colorProvider': {}, 'publishDiagnostics': {'relatedInformation': True}}}, 'rootPath': '/home/raoul/.config/sublime-text-3/Packages/LSP', 'workspaceFolders': [{'name': 'LSP', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}, {'name': 'LSP-eslint', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP-eslint'}, {'name': 'metals-sublime', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/metals-sublime'}, {'name': 'tonic', 'uri': 'file:///home/raoul/Documents/Programming/tonic'}, {'name': 'User', 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/User'}], 'processId': 16833, 'rootUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}
microsoft-python-language-server: GetCurrentSearchPaths /usr/bin/python3 
microsoft-python-language-server: Interpreter search paths:
microsoft-python-language-server:     /usr/lib/python3.7
microsoft-python-language-server:     /usr/lib/python3.7/lib-dynload
microsoft-python-language-server:     /home/raoul/.local/lib/python3.7/site-packages
microsoft-python-language-server:     /usr/local/lib/python3.7/dist-packages
microsoft-python-language-server:     /usr/lib/python3/dist-packages
microsoft-python-language-server: User search paths:
microsoft-python-language-server: Initializing for /usr/bin/python3
microsoft-python-language-server: Analysis caching mode: None.
:: <<< microsoft-python-language-server 1: {'capabilities': {'documentHighlightProvider': False, 'declarationProvider': True, 'documentFormattingProvider': False, 'documentRangeFormattingProvider': False, 'documentSymbolProvider': True, 'textDocumentSync': {'openClose': True, 'willSave': False, 'change': 2, 'willSaveWaitUntil': False}, 'hoverProvider': True, 'codeActionProvider': {'codeActionKinds': ['quickfix', 'refactor']}, 'workspaceSymbolProvider': True, 'documentOnTypeFormattingProvider': {'moreTriggerCharacter': [';', ':'], 'firstTriggerCharacter': '\n'}, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'signatureHelpProvider': {'triggerCharacters': ['(', ',', ')']}, 'renameProvider': True, 'definitionProvider': True, 'referencesProvider': True}}
::  -> microsoft-python-language-server workspace/didChangeConfiguration: {'settings': {'python': {'analysis': {'warnings': ['unknown-parameter-name'], 'information': ['unresolved-import'], 'errors': ['undefined-variable'], 'disabled': ['too-many-function-arguments', 'parameter-missing']}}}}
::  -> microsoft-python-language-server initialized: {}
::  -> microsoft-python-language-server textDocument/didOpen
:: <-- microsoft-python-language-server workspace/configuration(2): {'items': [{'section': 'python', 'scopeUri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP'}]}
:: >>> microsoft-python-language-server 2: [{'analysis': {'warnings': ['unknown-parameter-name'], 'information': ['unresolved-import'], 'errors': ['undefined-variable'], 'disabled': ['too-many-function-arguments', 'parameter-missing']}}]
:: <?  microsoft-python-language-server python/languageServerStarted: []
:: <?  microsoft-python-language-server python/beginProgress: []
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 30 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 62 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 35 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 24 items left...']
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [{'range': {'start': {'line': 0, 'character': 7}, 'end': {'line': 0, 'character': 14}}, 'severity': 3, 'source': 'Python', 'message': "unresolved import 'sublime'", 'code': 'unresolved-import'}, {'range': {'start': {'line': 1, 'character': 7}, 'end': {'line': 1, 'character': 21}}, 'severity': 3, 'source': 'Python', 'message': "unresolved import 'sublime_plugin'", 'code': 'unresolved-import'}], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/completion.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/documents.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/configurations.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/registry.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/workspace.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/clients.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/views.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/typing.py'}
:: <-  microsoft-python-language-server textDocument/publishDiagnostics: {'diagnostics': [], 'uri': 'file:///home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/settings.py'}
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 103 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 43 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 38 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 29 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 15 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 185 items left...']
:: <?  microsoft-python-language-server python/reportProgress: ['Analyzing in background, 131 items left...']
```

```js
Your final client configuration should look something like this:

		"microsoft-python-language-server":
		{
			"command": ["/home/raoul/dev/microsoft-python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer"],
			"enabled": true,
			"initializationOptions": {
				"interpreter": {
					"properties": {
						"interpreterPath": "/usr/bin/python3",
						"version": "3.7.5"
					}
				}
			},
			"languages": [
				{"languageId": "python", "scopes": ["source.python"], "syntaxes": ["Packages/Python/Python.sublime-syntax"]}
			],
			"env": {
				"DOTNET_ROOT": "/snap/dotnet-sdk/current"
			},
			"settings": {
				"python": {
					"analysis": {
						"errors": ["undefined-variable"],
						"warnings": ["unknown-parameter-name"],
						"information": ["unresolved-import"],
						"disabled": ["too-many-function-arguments", "parameter-missing"]
					}
				}
			}
		},
```

**Comment by desilinguist** [comment]
Thank you so much! The latest LSP package works fine now once I added the specific python analysis settings.

**Comment by rwols** [comment]
Latest version of microsoft-python-language-server apparently provides defaults now.
