### ISSUE TITLE
Something goes wrong with displaying signature help

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP#982]
```
Error handling server payload
Traceback (most recent call last):
  File "/Users/../Packages/LSP/plugin/core/rpc.py", line 215, in receive_payload
    self.response_handler(payload)
  File "/Users/../Packages/LSP/plugin/core/rpc.py", line 236, in response_handler
    handler(result)
  File "/Users/../Packages/LSP/plugin/signature_help.py", line 103, in <lambda>
    lambda response: self.handle_response(response, point))
  File "/Users/../Packages/LSP/plugin/signature_help.py", line 107, in handle_response
    self._help = create_signature_help(response)
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 179, in create_signature_help
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 179, in <genexpr>
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 114, in parse_signature_information
    paren_bounds = parse_signature_label(signature_label, param_infos)
  File "/Users/../Packages/LSP/plugin/core/signature_help.py", line 84, in parse_signature_label
    if signature_label[current_index] != ',':
IndexError: string index out of range
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/153197/80227262-ae1d9700-864d-11ea-8437-51bfe6123322.gif)

**Comment by rwols** [comment]
@rchl can you paste the signature help payload?

**Comment by rcjsuen** [comment]
> Looks like we assume that the `signature_label` string has the form `... , ...` somehow. That's a bug for us :)

Ooo, I can see that assumption not working out for Dockerfiles. :P

**Comment by rwols** [comment]
For reference:
```
{
    "activeSignature": 0,
    "activeParameter": 0,
    "signatures": [
        {
            "label": "RUN command parameter ...",
            "parameters": [
                {
                    "label": "command",
                    "documentation": "The command to run."
                },
                {
                    "label": "parameter",
                    "documentation": "A parameter to the command."
                },
                {
                    "label": "...",
                    "documentation": "A parameter to the command."
                }
            ],
            "documentation": "Execute commands inside a shell."
        },
        {
            "label": "RUN [ \"command\", \"parameter\", ... ]",
            "parameters": [
                {
                    "label": "["
                },
                {
                    "label": "\"command\"",
                    "documentation": "The command to run."
                },
                {
                    "label": "\"parameter\"",
                    "documentation": "A parameter to the command."
                },
                {
                    "label": "...",
                    "documentation": "A parameter to the command."
                },
                {
                    "label": "]"
                }
            ],
            "documentation": "Execute commands without invoking a command shell."
        }
    ]
}
```

**Comment by rwols** [comment]
I can also reproduce this in the console :) so we have pinned down the problem

```
>>> from LSP.plugin.core.signature_help import create_signature_help
>>> create_signature_help({'activeSignature': 0, 'activeParameter': 0, 'signatures': [{'label': 'RUN command parameter ...', 'parameters': [{'label': 'command', 'documentation': 'The command to run.'}, {'label': 'parameter', 'documentation': 'A parameter to the command.'}, {'label': '...', 'documentation': 'A parameter to the command.'}], 'documentation': 'Execute commands inside a shell.'}, {'label': 'RUN [ "command", "parameter", ... ]', 'parameters': [{'label': '['}, {'label': '"command"', 'documentation': 'The command to run.'}, {'label': '"parameter"', 'documentation': 'A parameter to the command.'}, {'label': '...', 'documentation': 'A parameter to the command.'}, {'label': ']'}], 'documentation': 'Execute commands without invoking a command shell.'}]})
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/signature_help.py", line 184, in create_signature_help
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/signature_help.py", line 184, in <genexpr>
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/signature_help.py", line 119, in parse_signature_information
    paren_bounds = parse_signature_label(signature_label, param_infos)
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/signature_help.py", line 89, in parse_signature_label
    if signature_label[current_index] != ',':
IndexError: string index out of range
```

**Comment by rwols** [comment]
A smaller repro:
```
create_signature_help({'activeSignature': 0, 'activeParameter': 0, 'signatures': [{'label': 'RUN [ "command", ... ]', 'parameters': [{'label': '['}, {'label': '"command"'}, {'label': '...'}, {'label': ']'}]}]})
```
